---
title: "pRSA-s2-rwebppl"
author: "M. H. Tessler, Erica Yoon"
date: "1/9/2017"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(binom)
library(rwebppl)
library(jsonlite)
library(readr)
knitr::opts_chunk$set(echo = TRUE)
library(coda)
library(magrittr)
library(ggthemes)
library(forcats)

# set path to working dir
local.path <- "~/Documents/Research/cogsci2017/"

estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}
# HPDhi<- function(s){
hdi_upper <- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}
# HPDlo<- function(s){
hdi_lower <- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}
options("scipen"=10)   
```

# Literal semantics data

```{r eval=FALSE}
d.lit <- read.csv(paste(local.path,
"experiments/processed_data/literalSemantics_wNeg.csv",
                        sep = ""))
```

Summarize behavioral data (in terms of number of "yes"es)

```{r eval=FALSE}
d.lit.summary <- d.lit %>%
  group_by(state, utterance) %>%
  summarize(k = sum(judgment),
            n = n())
```

Binomial is conjugate to Beta, we can solve for the posterior analytically

```{r}
d.lit.summary <- d.lit.summary %>%
  mutate(posterior_b1 = 1 + k,
         posterior_b2 = 1 + n - k, 
         MAP = (posterior_b1 - 1) / (posterior_b1 + posterior_b2 - 2),
          cred_low  = qbeta(.025, posterior_b1, posterior_b2),
         cred_upper = qbeta(.975, posterior_b1, posterior_b2))
```

# Polite RSA + data analysis model

```{r}
fullModel <- '
var utterances = ["yes_terrible","yes_bad","yes_okay","yes_good","yes_amazing",
                  "not_terrible","not_bad","not_okay","not_good","not_amazing"
                  ];

var states = [1,2,3,4,5];

var statePrior = function(){
  return uniformDraw(states);
};

var isNegation = function(utt){
  return (utt.split("_")[0] == "not")
};

// measured in Experiment 1
var literalSemantics = dataFromR.literalSemantics;

 var litSemanticsPosteriorObj = _.object(map(function(u){
  return [u, _.object(map(function(s){
      var litParams = _.where(literalSemantics, {state: s, utterance: u})[0]
    return [s, {a: litParams.posterior_b1, b: litParams.posterior_b2}]
 }, states))]
 }, utterances))

var round = function(x){
	return Math.round(x * 100) / 100
}

var weightBins = map(round, _.range(0.0001, 1, 0.05))
var phiWeights = repeat(weightBins.length, function(){1})
  
var goalWeightPrior = Infer({method: "enumerate"}, function(){
  return uniformDraw(weightBins);
})

var nBins = weightBins.length;
var kernelWidth = nBins / 4;

var kernelFn = function(prevVal){
  var i = weightBins.indexOf(prevVal);
  var upper = (i + kernelWidth) > nBins ? nBins : i + kernelWidth;
  var lower = (i - kernelWidth) < 0 ? 0 : i - kernelWidth;
  return Categorical({vs: weightBins.slice(lower,upper), 
                      ps: phiWeights.slice(lower,upper)})
}


var data = dataFromR.data;

var goals = _.uniq(_.pluck(data, "goal"));

var states = _.uniq(_.pluck(data, "true_state"));

var dataAnalysis = function(){
    
    var litSemantics = _.object(map(function(u){
    	return [u, _.object(map(function(s){
        var litParams = litSemanticsPosteriorObj[u][s];
         return [s, beta(litParams)]
      }, states))]
     }, utterances))

    var RSAparameters = {
      speakerOptimality: uniformDrift({a: 0, b: 20, width:2}),
      speakerOptimality2: uniformDrift({a:0, b: 5, width: 0.5}),
      alpha: uniformDrift({a: 0, b: 5, width:0.5}),
      cost: uniformDrift({a: 1, b: 10, width:0.25})
    };

    var cost_yes = 1;
    var uttCosts = map(function(u) {return isNegation(u) ? Math.exp(-RSAparameters.cost) : Math.exp(-cost_yes)},
            utterances)
    
    var utterancePrior = Infer({method: "enumerate"}, function(){
      return  utterances[discrete(uttCosts)];
    });

    var meaning = function(words, state){
      return flip(litSemantics[words][state]);
    }; 
    
    var listener0 = cache(function(utterance) {
      Infer({method: "enumerate"}, function(){
        var state = uniformDraw(states);
        var m = meaning(utterance, state);
        condition(m);
        return state;
      });
    }, 10000);
    
    var speaker1 = cache(function(state, speakerGoals) {
      Infer({method: "enumerate"}, function(){
        var utterance = sample(utterancePrior);
    
        var speakerOptimality = RSAparameters.speakerOptimality;
        var alpha = RSAparameters.alpha;
    
        var L0 = listener0(utterance);
        
        var epistemicUtility = L0.score(state);
        var socialUtility = expectation(L0, function(s){return alpha*s});
        
        var eUtility = speakerGoals.phi*epistemicUtility;
        var sUtility = (1-speakerGoals.phi)*socialUtility;
    
        var speakerUtility = eUtility+sUtility;
    
        factor(speakerOptimality*speakerUtility);
        
        return utterance;
      })
    }, 10000)
    
    var listener1 = cache(function(utterance) {
     Infer({method: "enumerate"}, function(){
    
       var speakerGoals = {
         phi:categorical ({vs: weightBins, ps: phiWeights})
       }
       
       var state = uniformDraw(states);
    
       var S1 = speaker1(state, speakerGoals)
       observe(S1, utterance)
        
       return {
         state: state,
         goals: speakerGoals
       }
        })
    }, 10000)
    
    var speaker2 = cache(function(exptCondInfo) {
     Enumerate(function(){
       var state = exptCondInfo.state;
       var intendedGoals = exptCondInfo.goalWeights;
       var utterance = sample(utterancePrior);
    
       var L1 = listener1(utterance)
    
       factor(RSAparameters.speakerOptimality2 * L1.score({"state":state, "goals":intendedGoals}))

       return utterance
    
     })
    }, 10000)



    var goalWeightsAndPostPred = map(function(goal){
      
      var goalWeights = {
        phi: sample(goalWeightPrior, {driftKernel: kernelFn})
      }

    var postPred = map(function(state){
      
     var utteranceData = _.pluck(_.where(data, {true_state: state, goal: goal}), "utterance"); 

      var exptConditionInfo = {
        state: state, 
        utterance: false,
        goalWeights: goalWeights
      };

      var RSApredictions = speaker2(exptConditionInfo);

      mapData({data: utteranceData}, 
          function(d){ 
               // display(RSApredictions.score(d))
              observe(RSApredictions, d) 
          });

      var postSupport = RSApredictions.support(); // all utterances in the posterior

      var postPredictive = map(function(u){
        return {
          key: "posteriorPredictive",
          goal: goal,
          state: state,
          utt: u,
          val: Math.exp(RSApredictions.score(u))
        }
      }, postSupport)

      var negative_utterances = [
        "not_terrible","not_bad","not_okay","not_good","not_amazing"
      ]

      var negEndorsement = sum(map(function(u){
          return Math.exp(RSApredictions.score(u))
      }, negative_utterances))
      
      return _.flatten([postPredictive, {
          key: "posteriorPredictive",
          goal: goal,
          state: state,
          utt: "negation",
          val: negEndorsement
        }])
      
    }, states)

    return [postPred, 
            {key: "phi", goal: goal, state: "NA", utt: "NA", val: goalWeights.phi},
            //{key: "weightHonest", goal: goal, state: "NA", utt: "NA", val: goalWeights.honesty},
            //{key: "weightKind", goal: goal, state: "NA", utt: "NA", val: goalWeights.kindness}
            ]
    
  }, goals)

  var returnList = _.flatten([goalWeightsAndPostPred, 
                              //litSemantics,
                              {key: "speakerOptimality", goal: "NA", utt: "NA", state: "NA", val: RSAparameters.speakerOptimality},
                              {key: "speakerOptimality2", goal: "NA", utt: "NA", state: "NA", val: RSAparameters.speakerOptimality2},
                              {key: "alpha", goal: "NA", utt: "NA", state: "NA", val: RSAparameters.alpha},
                              {key: "cost", goal: "NA", utt: "NA", state: "NA", val: RSAparameters.cost}
                              ])
  
  var returnObj = _.object(map(function(i){
    [i.key + "_" + i.goal + "_" + i.state + "_" + i.utt, i.val]
  }, returnList))

  return returnObj
    
}

'
```


Run Full BDA model

```{r}
bda.utterance.results <- data.frame()

litSemantics.toPass <- d.lit.summary %>% select(-k, -n)
dataToWebPPL <- list(literalSemantics = litSemantics.toPass,
                     data = d.utterance)

numSamples <- 400
nChains <- 2
bda.utterance.results <- webppl(fullModel,
                            data = dataToWebPPL,
                            data_var = "dataFromR",
                            inference_opts = list(method = "MCMC", 
                                                #  kernel = list(HMC = list(steps = 5, stepSize = 0.001)),
                                                  samples = numSamples,
                                                  burn = numSamples/2,
                                                  verbose = TRUE),
                            model_var = "dataAnalysis",
                            output_format = "samples",
                            chains = nChains,
                            cores = nChains)
```
